fix: repositioning by cue config
kaltura/playkit-js pull request #515
Opened 2020-12-03 08:54 UTC by Yuvalke

### Description of the Changes

Issue: can't change cue visibility by config.
Solution: add config and use our API.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2020-12-03 09:08 UTC, dan-ziv requested changes

2020-12-03 09:08 UTC, dan-ziv commented on flow-typed/types/playback-config.js
> +  TextTrackDisplaySetting: Cue
`textTrackDisplaySetting `

2020-12-03 10:24 UTC, dan-ziv requested changes

2020-12-03 10:31 UTC, Yuvalke commented on src/player.js
> +    this.setTextDisplaySettings(this._config.playback.TextTrackDisplaySetting);
So we'll be able to clear previous configuration

2020-12-03 10:31 UTC, OrenMe commented on src/player.js
> +  setTextDisplaySettings(settings: Cue): void {
Right, it should either be cue configuration object and in any case it is partial config as we don't request to pass full one.
This whole api is not final so we can continue with object.

2020-12-07 15:30 UTC, OrenMe commented
we will do a more general solution on FEC-10766

2020-12-08 09:24 UTC, closed without merging