fix(REACH2-919): correct order of captions that has the same time
kaltura/playkit-js pull request #530
Opened 2021-01-13 12:33 UTC by semarche-kaltura

### Description of the Changes

For captions with the same time player renders subtitles in wrong order. (https://kaltura.atlassian.net/browse/REACH2-919)
Current fix change the order of iteration and subtitles displays correctly.

<img width="323" alt="Screen Shot 2021-01-12 at 11 56 04 AM" src="https://user-images.githubusercontent.com/51074448/104452486-be92ea80-55ab-11eb-9131-c6c451e8c6ad.png">

<img width="646" alt="Screen Shot 2021-01-12 at 11 55 41 AM" src="https://user-images.githubusercontent.com/51074448/104452470-ba66cd00-55ab-11eb-9004-c8724df6c382.png">

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2021-01-13 12:48 UTC, RoyBregman commented
check with Oren, but i think it is better to open a FEC ticket and link them and solve this as part of FEC project

2021-01-13 13:14 UTC, yairans approved these changes

2021-01-13 13:58 UTC, OrenMe requested changes
I want to make sure we are actually doing the correct change.
Need to check in spec if it is legal to have such format of separate VTT cues at the exact same times.
The proper solution is to combine them and manage the ordering at the same place.
AFAICS this is the real order of the cues as inserted by the engine.

A good place to compare is to try this in Safari and see how it handles it.

2021-02-03 13:06 UTC, OrenMe commented
this is a marginal issue, if there are captions at same time the WebVTT spec doesn't mandate what order they should be stacked and in general for such a use case you would expect the captions to be merged.
Another approach is by defining the line or region for the captions - although we do not currently support VTT regions.

2021-02-03 13:06 UTC, closed without merging