fix(FEC-11509): fontSize is not working
kaltura/playkit-js pull request #601
Opened 2021-08-24 12:25 UTC by lianbenjamin

### Description of the Changes

**issue:**
fontSize configuration is not in use.

**solution:**
removing fontSize configuration.

Solves FEC-11509

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2021-08-24 12:50 UTC, yairans approved these changes

2021-09-05 18:53 UTC, SivanA-Kaltura commented
@lianbenjamin I also came across this issue because of a ticket I'm working on, FEC-11510. Please note that fontSize is used in https://github.com/kaltura/kaltura-player-js/blob/master/src/common/cast/text-style-convertor.js. We probably can remove this use and replace it with fontScale, but we need to check cast receiver and sender first.

2021-09-05 18:56 UTC, SivanA-Kaltura commented
@lianbenjamin fontSize is also used in https://github.com/kaltura/kaltura-player-js/blob/master/test/src/setup.spec.js

2021-09-05 18:57 UTC, SivanA-Kaltura commented on flow-typed/types/text-style.js
> -  fontSize: string,
Please see my comments about uses in kaltura-player-js

2021-09-06 07:27 UTC, SivanA-Kaltura requested changes

2021-09-06 07:27 UTC, SivanA-Kaltura commented on src/track/text-style.js
>        fontScale: text.fontScale,
fontSize is referenced in api.md, so after fontSize is removed the docs should be rebuilt by running yarn run docs:generate

2021-09-06 07:53 UTC, SivanA-Kaltura requested changes

2021-09-06 07:53 UTC, SivanA-Kaltura commented on src/track/text-style.js
>    fontScale: number = 1;
since the jsdoc has been modified, please rebuild api.md by running "yarn run docs:generate"

2021-09-26 08:25 UTC, OrenMe commented
@SivanA-Kaltura , @lianbenjamin as we decided to keep fontSize and fix the implementation then closing this one

2021-09-26 08:25 UTC, closed without merging