fix(FEC-11606): merge active cue-points from all metadata TextTracks
kaltura/playkit-js pull request #610
Opened 2021-10-11 15:53 UTC by semarche-kaltura

### Description of the Changes

Merge active cue-points from all metadata TextTracks for TIMED_METADATA payload

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2021-11-01 07:14 UTC, OrenMe commented on src/engines/html5/html5.js
> +        this.dispatchEvent(new FakeEvent(CustomEventType.TIMED_METADATA, {cues: activeCues}));
@yairans @semarche-kaltura any update?

2021-11-28 23:07 UTC, semarche-kaltura commented
@OrenMe, @yairans PR updated

2021-11-29 10:27 UTC, yairans requested changes

2021-11-29 10:27 UTC, yairans commented on src/engines/html5/html5.js
> +            activeCues = activeCues.concat(getActiveCues(track.activeCues));
as already discussed the cues should be sorted

2021-11-29 11:13 UTC, yairans approved these changes

2021-12-06 16:02 UTC, semarche-kaltura commented on src/engines/html5/html5.js
> +        this.dispatchEvent(new FakeEvent(CustomEventType.TIMED_METADATA, {cues: activeCues}));
@OrenMe PR updated

2021-12-08 11:56 UTC, yairans requested changes

2021-12-08 11:56 UTC, yairans commented on src/engines/html5/html5.js
>      const metadataTrack = Array.from(this._el.textTracks).find((track: TextTrack) => PKTextTrack.isMetaDataTrack(track));
need to change this `find` to `filter` as we now have multiple metadata tracks.
I don't know how it's working with id3 and cuepoints. maybe it get to the 'addtrack' event in the 'else' block below

2022-01-11 13:57 UTC, yairans commented
implemented as part of https://github.com/kaltura/playkit-js/pull/623

2022-01-11 13:57 UTC, closed without merging