fix(FEC-12752) - ignore userCache for textLanguage if it is disabled
kaltura/playkit-js pull request #679
Opened 2022-11-21 19:28 UTC by giladna

### Description of the Changes

Fix FEC-12752 was introduced in FEC-10833

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2022-11-22 07:22 UTC, lianbenjamin approved these changes

2022-11-24 12:53 UTC, JonathanTGold commented on src/player.js
> +        const activeTracks = this.getActiveTracks();
the issue regarding FEC-1111 can be fix without accessing the cache just by reverse the order of the condition 
`const currentOrConfiguredTextLang =
  this._getLanguage<TextTrack>(this._getTextTracks(), playbackConfig.textLanguage, activeTracks.text) ||
  this._playbackAttributesState.textLanguage;`

2022-11-27 12:17 UTC, SivanA-Kaltura requested changes

2022-11-27 12:58 UTC, giladna commented on src/player.js
> +        : this._playbackAttributesState.textLanguage || defaultLanguage;
done

2022-11-27 13:47 UTC, SivanA-Kaltura approved these changes

2022-11-27 13:49 UTC, merged